import Head from 'next/head';
import TodoLister from '@/components/TodoLister';

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo List App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <TodoLister />
    </>
  )
}